// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a0f6d15d-70c7-474f-91cc-6b20786e8083";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCongNamChange();
void onAutoModeChange();
void onCongDongChange();
void onCongTayChange();
void onNhietDoChange();

CloudLight congNam;
CloudSwitch autoMode;
CloudSwitch congDong;
CloudSwitch congTay;
CloudTemperatureSensor nhietDo;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(congNam, READWRITE, ON_CHANGE, onCongNamChange);
  ArduinoCloud.addProperty(autoMode, READWRITE, ON_CHANGE, onAutoModeChange);
  ArduinoCloud.addProperty(congDong, READWRITE, ON_CHANGE, onCongDongChange);
  ArduinoCloud.addProperty(congTay, READWRITE, ON_CHANGE, onCongTayChange);
  ArduinoCloud.addProperty(nhietDo, READWRITE, ON_CHANGE, onNhietDoChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
